// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy4M3j9g2KQ7E8zuHbh5Hw1hHYlMMVDPM',
    appId: '1:886189315502:web:837c7265ed104c9f0b643f',
    messagingSenderId: '886189315502',
    projectId: 'dexkorchatapp',
    authDomain: 'dexkorchatapp.firebaseapp.com',
    storageBucket: 'dexkorchatapp.appspot.com',
    measurementId: 'G-MVBBZQZW51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlODLdakNwJSnv5o4Yx5VmSRvFFc6q6c',
    appId: '1:886189315502:android:84903edf42894ea70b643f',
    messagingSenderId: '886189315502',
    projectId: 'dexkorchatapp',
    storageBucket: 'dexkorchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8F_quwhDPOZaE8FzY7T38s52zp3DPUms',
    appId: '1:886189315502:ios:cdfc22085769f8750b643f',
    messagingSenderId: '886189315502',
    projectId: 'dexkorchatapp',
    storageBucket: 'dexkorchatapp.appspot.com',
    iosClientId:
        '886189315502-t2dpeq29jbn75ggpun21t2h33kpr32vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
